name: Build & Push to DockerHub

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: DockerHub login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build & push
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ashia-nest:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ashia-nest:latest
